/*
 * generated by Xtext
 */
package it.unifi.xtext.facpl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Facpl2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return it.unifi.xtext.facpl.ui.internal.Facpl2Activator.getInstance()
				.getInjector("it.unifi.xtext.facpl.Facpl2");
	}

}
