/*
 * generated by Xtext
 */
package it.unifi.xtext.facpl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Facpl2AntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("it/unifi/xtext/facpl/parser/antlr/internal/InternalFacpl2.tokens");
	}
}
