/*
 * generated by Xtext
 */
package it.unifi.xtext.facpl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import it.unifi.xtext.facpl.services.Facpl2GrammarAccess;

public class Facpl2Parser extends AbstractContentAssistParser {
	
	@Inject
	private Facpl2GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected it.unifi.xtext.facpl.ui.contentassist.antlr.internal.InternalFacpl2Parser createParser() {
		it.unifi.xtext.facpl.ui.contentassist.antlr.internal.InternalFacpl2Parser result = new it.unifi.xtext.facpl.ui.contentassist.antlr.internal.InternalFacpl2Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAttributeAccess().getAlternatives(), "rule__Attribute__Alternatives");
					put(grammarAccess.getAttributeAccess().getXAlternatives_2_3_0(), "rule__Attribute__XAlternatives_2_3_0");
					put(grammarAccess.getAttributeAccess().getXAlternatives_3_3_0(), "rule__Attribute__XAlternatives_3_3_0");
					put(grammarAccess.getPepFunctionAccess().getAlternatives(), "rule__PepFunction__Alternatives");
					put(grammarAccess.getPepFunctionAccess().getValueAlternatives_8_4_0(), "rule__PepFunction__ValueAlternatives_8_4_0");
					put(grammarAccess.getPepFunctionAccess().getValueAlternatives_9_4_0(), "rule__PepFunction__ValueAlternatives_9_4_0");
					put(grammarAccess.getObligationAccess().getTypeOblAlternatives_2_0(), "rule__Obligation__TypeOblAlternatives_2_0");
					put(grammarAccess.getObligationAccess().getAlternatives_3(), "rule__Obligation__Alternatives_3");
					put(grammarAccess.getObligationAccess().getAlternatives_3_0(), "rule__Obligation__Alternatives_3_0");
					put(grammarAccess.getSTRING_OAccess().getAlternatives_1_0(), "rule__STRING_O__Alternatives_1_0");
					put(grammarAccess.getFacplPolicyAccess().getAlternatives(), "rule__FacplPolicy__Alternatives");
					put(grammarAccess.getAbstractPolicyInclAccess().getAlternatives(), "rule__AbstractPolicyIncl__Alternatives");
					put(grammarAccess.getBasicExpressionAccess().getAlternatives(), "rule__BasicExpression__Alternatives");
					put(grammarAccess.getFunctionAccess().getAlternatives_2(), "rule__Function__Alternatives_2");
					put(grammarAccess.getFunctionAccess().getAlternatives_4(), "rule__Function__Alternatives_4");
					put(grammarAccess.getLiteralsAccess().getAlternatives(), "rule__Literals__Alternatives");
					put(grammarAccess.getTypeLiteralAccess().getAlternatives(), "rule__TypeLiteral__Alternatives");
					put(grammarAccess.getPEPAlgAccess().getAlternatives(), "rule__PEPAlg__Alternatives");
					put(grammarAccess.getAlgLiteralAccess().getAlternatives(), "rule__AlgLiteral__Alternatives");
					put(grammarAccess.getFulfillmentStrategyAccess().getAlternatives(), "rule__FulfillmentStrategy__Alternatives");
					put(grammarAccess.getEffectAccess().getAlternatives(), "rule__Effect__Alternatives");
					put(grammarAccess.getFunIDAccess().getAlternatives(), "rule__FunID__Alternatives");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getMainFacplAccess().getGroup(), "rule__MainFacpl__Group__0");
					put(grammarAccess.getMainFacplAccess().getGroup_6(), "rule__MainFacpl__Group_6__0");
					put(grammarAccess.getMainFacplAccess().getGroup_7(), "rule__MainFacpl__Group_7__0");
					put(grammarAccess.getMainFacplAccess().getGroup_7_2(), "rule__MainFacpl__Group_7_2__0");
					put(grammarAccess.getMainFacplAccess().getGroup_7_2_1(), "rule__MainFacpl__Group_7_2_1__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup(), "rule__FunctionDeclaration__Group__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup_5(), "rule__FunctionDeclaration__Group_5__0");
					put(grammarAccess.getPAFAccess().getGroup(), "rule__PAF__Group__0");
					put(grammarAccess.getSTATUSAccess().getGroup(), "rule__STATUS__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_0(), "rule__Attribute__Group_0__0");
					put(grammarAccess.getAttributeAccess().getGroup_1(), "rule__Attribute__Group_1__0");
					put(grammarAccess.getAttributeAccess().getGroup_2(), "rule__Attribute__Group_2__0");
					put(grammarAccess.getAttributeAccess().getGroup_3(), "rule__Attribute__Group_3__0");
					put(grammarAccess.getAttributeAccess().getGroup_4(), "rule__Attribute__Group_4__0");
					put(grammarAccess.getAttributeDeclarationAccess().getGroup(), "rule__AttributeDeclaration__Group__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_0(), "rule__PepFunction__Group_0__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_1(), "rule__PepFunction__Group_1__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_2(), "rule__PepFunction__Group_2__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_3(), "rule__PepFunction__Group_3__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_4(), "rule__PepFunction__Group_4__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_5(), "rule__PepFunction__Group_5__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_6(), "rule__PepFunction__Group_6__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_7(), "rule__PepFunction__Group_7__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_8(), "rule__PepFunction__Group_8__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_9(), "rule__PepFunction__Group_9__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_10(), "rule__PepFunction__Group_10__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_11(), "rule__PepFunction__Group_11__0");
					put(grammarAccess.getPepFunctionAccess().getGroup_12(), "rule__PepFunction__Group_12__0");
					put(grammarAccess.getObligationAccess().getGroup(), "rule__Obligation__Group__0");
					put(grammarAccess.getObligationAccess().getGroup_3_0_0(), "rule__Obligation__Group_3_0_0__0");
					put(grammarAccess.getObligationAccess().getGroup_3_0_0_2(), "rule__Obligation__Group_3_0_0_2__0");
					put(grammarAccess.getObligationAccess().getGroup_3_0_0_2_1(), "rule__Obligation__Group_3_0_0_2_1__0");
					put(grammarAccess.getObligationAccess().getGroup_3_1(), "rule__Obligation__Group_3_1__0");
					put(grammarAccess.getObligationAccess().getGroup_3_1_3(), "rule__Obligation__Group_3_1_3__0");
					put(grammarAccess.getRequestAccess().getGroup(), "rule__Request__Group__0");
					put(grammarAccess.getRequestAccess().getGroup_1(), "rule__Request__Group_1__0");
					put(grammarAccess.getAttributeReqAccess().getGroup(), "rule__AttributeReq__Group__0");
					put(grammarAccess.getAttributeReqAccess().getGroup_4(), "rule__AttributeReq__Group_4__0");
					put(grammarAccess.getAttributeNameAccess().getGroup(), "rule__AttributeName__Group__0");
					put(grammarAccess.getSTRING_OAccess().getGroup(), "rule__STRING_O__Group__0");
					put(grammarAccess.getSTRING_OAccess().getGroup_1(), "rule__STRING_O__Group_1__0");
					put(grammarAccess.getPDPAccess().getGroup(), "rule__PDP__Group__0");
					put(grammarAccess.getAbstractPolicyInclAccess().getGroup_1(), "rule__AbstractPolicyIncl__Group_1__0");
					put(grammarAccess.getPolicySetAccess().getGroup(), "rule__PolicySet__Group__0");
					put(grammarAccess.getPolicySetAccess().getGroup_4(), "rule__PolicySet__Group_4__0");
					put(grammarAccess.getPolicySetAccess().getGroup_7(), "rule__PolicySet__Group_7__0");
					put(grammarAccess.getAlgAccess().getGroup(), "rule__Alg__Group__0");
					put(grammarAccess.getAlgAccess().getGroup_1(), "rule__Alg__Group_1__0");
					put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
					put(grammarAccess.getRuleAccess().getGroup_4(), "rule__Rule__Group_4__0");
					put(grammarAccess.getRuleAccess().getGroup_5(), "rule__Rule__Group_5__0");
					put(grammarAccess.getAndExpressionAccess().getGroup(), "rule__AndExpression__Group__0");
					put(grammarAccess.getAndExpressionAccess().getGroup_1(), "rule__AndExpression__Group_1__0");
					put(grammarAccess.getOrExpressionAccess().getGroup(), "rule__OrExpression__Group__0");
					put(grammarAccess.getOrExpressionAccess().getGroup_1(), "rule__OrExpression__Group_1__0");
					put(grammarAccess.getBasicExpressionAccess().getGroup_2(), "rule__BasicExpression__Group_2__0");
					put(grammarAccess.getNotExpressionAccess().getGroup(), "rule__NotExpression__Group__0");
					put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
					put(grammarAccess.getFunctionAccess().getGroup_2_1(), "rule__Function__Group_2_1__0");
					put(grammarAccess.getFunctionAccess().getGroup_4_1(), "rule__Function__Group_4_1__0");
					put(grammarAccess.getDeclaredFunctionAccess().getGroup(), "rule__DeclaredFunction__Group__0");
					put(grammarAccess.getDeclaredFunctionAccess().getGroup_3(), "rule__DeclaredFunction__Group_3__0");
					put(grammarAccess.getSetAccess().getGroup(), "rule__Set__Group__0");
					put(grammarAccess.getSetAccess().getGroup_1(), "rule__Set__Group_1__0");
					put(grammarAccess.getSetAccess().getGroup_1_1(), "rule__Set__Group_1_1__0");
					put(grammarAccess.getFacplAccess().getImportElAssignment_0(), "rule__Facpl__ImportElAssignment_0");
					put(grammarAccess.getFacplAccess().getDeclarationsAssignment_1(), "rule__Facpl__DeclarationsAssignment_1");
					put(grammarAccess.getFacplAccess().getPoliciesAssignment_2(), "rule__Facpl__PoliciesAssignment_2");
					put(grammarAccess.getFacplAccess().getRequestsAssignment_3(), "rule__Facpl__RequestsAssignment_3");
					put(grammarAccess.getFacplAccess().getMainAssignment_4(), "rule__Facpl__MainAssignment_4");
					put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
					put(grammarAccess.getMainFacplAccess().getExtIndetAssignment_4(), "rule__MainFacpl__ExtIndetAssignment_4");
					put(grammarAccess.getMainFacplAccess().getGenPackageAssignment_6_2(), "rule__MainFacpl__GenPackageAssignment_6_2");
					put(grammarAccess.getMainFacplAccess().getRefRequestAssignment_7_2_0(), "rule__MainFacpl__RefRequestAssignment_7_2_0");
					put(grammarAccess.getMainFacplAccess().getRefRequestAssignment_7_2_1_1(), "rule__MainFacpl__RefRequestAssignment_7_2_1_1");
					put(grammarAccess.getMainFacplAccess().getPafAssignment_8(), "rule__MainFacpl__PafAssignment_8");
					put(grammarAccess.getFunctionDeclarationAccess().getTypeAssignment_1(), "rule__FunctionDeclaration__TypeAssignment_1");
					put(grammarAccess.getFunctionDeclarationAccess().getNameAssignment_2(), "rule__FunctionDeclaration__NameAssignment_2");
					put(grammarAccess.getFunctionDeclarationAccess().getArgsAssignment_4(), "rule__FunctionDeclaration__ArgsAssignment_4");
					put(grammarAccess.getFunctionDeclarationAccess().getArgsAssignment_5_1(), "rule__FunctionDeclaration__ArgsAssignment_5_1");
					put(grammarAccess.getPAFAccess().getStatusAssignment_0(), "rule__PAF__StatusAssignment_0");
					put(grammarAccess.getPAFAccess().getPepAssignment_2(), "rule__PAF__PepAssignment_2");
					put(grammarAccess.getPAFAccess().getPdpAssignment_4(), "rule__PAF__PdpAssignment_4");
					put(grammarAccess.getSTATUSAccess().getElementsAssignment_2(), "rule__STATUS__ElementsAssignment_2");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_0_0(), "rule__Attribute__TypeAssignment_0_0");
					put(grammarAccess.getAttributeAccess().getNameAssignment_0_1(), "rule__Attribute__NameAssignment_0_1");
					put(grammarAccess.getAttributeAccess().getXAssignment_0_3(), "rule__Attribute__XAssignment_0_3");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_1_0(), "rule__Attribute__TypeAssignment_1_0");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1_1(), "rule__Attribute__NameAssignment_1_1");
					put(grammarAccess.getAttributeAccess().getXAssignment_1_3(), "rule__Attribute__XAssignment_1_3");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_2_0(), "rule__Attribute__TypeAssignment_2_0");
					put(grammarAccess.getAttributeAccess().getNameAssignment_2_1(), "rule__Attribute__NameAssignment_2_1");
					put(grammarAccess.getAttributeAccess().getXAssignment_2_3(), "rule__Attribute__XAssignment_2_3");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_3_0(), "rule__Attribute__TypeAssignment_3_0");
					put(grammarAccess.getAttributeAccess().getNameAssignment_3_1(), "rule__Attribute__NameAssignment_3_1");
					put(grammarAccess.getAttributeAccess().getXAssignment_3_3(), "rule__Attribute__XAssignment_3_3");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_4_0(), "rule__Attribute__TypeAssignment_4_0");
					put(grammarAccess.getAttributeAccess().getNameAssignment_4_1(), "rule__Attribute__NameAssignment_4_1");
					put(grammarAccess.getAttributeAccess().getXAssignment_4_3(), "rule__Attribute__XAssignment_4_3");
					put(grammarAccess.getAttributeDeclarationAccess().getAttAssignment_1(), "rule__AttributeDeclaration__AttAssignment_1");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_0_0(), "rule__PepFunction__NameAssignment_0_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_0_2(), "rule__PepFunction__AttAssignment_0_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_0_4(), "rule__PepFunction__ValueAssignment_0_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_1_0(), "rule__PepFunction__NameAssignment_1_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_1_2(), "rule__PepFunction__AttAssignment_1_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_1_4(), "rule__PepFunction__ValueAssignment_1_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_2_0(), "rule__PepFunction__NameAssignment_2_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_2_2(), "rule__PepFunction__AttAssignment_2_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_2_4(), "rule__PepFunction__ValueAssignment_2_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_3_0(), "rule__PepFunction__NameAssignment_3_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_3_2(), "rule__PepFunction__AttAssignment_3_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_3_4(), "rule__PepFunction__ValueAssignment_3_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_4_0(), "rule__PepFunction__NameAssignment_4_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_4_2(), "rule__PepFunction__AttAssignment_4_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_4_4(), "rule__PepFunction__ValueAssignment_4_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_5_0(), "rule__PepFunction__NameAssignment_5_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_5_2(), "rule__PepFunction__AttAssignment_5_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_5_4(), "rule__PepFunction__ValueAssignment_5_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_6_0(), "rule__PepFunction__NameAssignment_6_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_6_2(), "rule__PepFunction__AttAssignment_6_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_6_4(), "rule__PepFunction__ValueAssignment_6_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_7_0(), "rule__PepFunction__NameAssignment_7_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_7_2(), "rule__PepFunction__AttAssignment_7_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_7_4(), "rule__PepFunction__ValueAssignment_7_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_8_0(), "rule__PepFunction__NameAssignment_8_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_8_2(), "rule__PepFunction__AttAssignment_8_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_8_4(), "rule__PepFunction__ValueAssignment_8_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_9_0(), "rule__PepFunction__NameAssignment_9_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_9_2(), "rule__PepFunction__AttAssignment_9_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_9_4(), "rule__PepFunction__ValueAssignment_9_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_10_0(), "rule__PepFunction__NameAssignment_10_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_10_2(), "rule__PepFunction__AttAssignment_10_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_10_4(), "rule__PepFunction__ValueAssignment_10_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_11_0(), "rule__PepFunction__NameAssignment_11_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_11_2(), "rule__PepFunction__AttAssignment_11_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_11_4(), "rule__PepFunction__ValueAssignment_11_4");
					put(grammarAccess.getPepFunctionAccess().getNameAssignment_12_0(), "rule__PepFunction__NameAssignment_12_0");
					put(grammarAccess.getPepFunctionAccess().getAttAssignment_12_2(), "rule__PepFunction__AttAssignment_12_2");
					put(grammarAccess.getPepFunctionAccess().getValueAssignment_12_4(), "rule__PepFunction__ValueAssignment_12_4");
					put(grammarAccess.getObligationAccess().getEvaluetedOnAssignment_1(), "rule__Obligation__EvaluetedOnAssignment_1");
					put(grammarAccess.getObligationAccess().getTypeOblAssignment_2(), "rule__Obligation__TypeOblAssignment_2");
					put(grammarAccess.getObligationAccess().getPepActionAssignment_3_0_0_0(), "rule__Obligation__PepActionAssignment_3_0_0_0");
					put(grammarAccess.getObligationAccess().getExprAssignment_3_0_0_2_0(), "rule__Obligation__ExprAssignment_3_0_0_2_0");
					put(grammarAccess.getObligationAccess().getExprAssignment_3_0_0_2_1_1(), "rule__Obligation__ExprAssignment_3_0_0_2_1_1");
					put(grammarAccess.getObligationAccess().getFunctionAssignment_3_0_1(), "rule__Obligation__FunctionAssignment_3_0_1");
					put(grammarAccess.getObligationAccess().getE1Assignment_3_1_0(), "rule__Obligation__E1Assignment_3_1_0");
					put(grammarAccess.getObligationAccess().getE2Assignment_3_1_2(), "rule__Obligation__E2Assignment_3_1_2");
					put(grammarAccess.getObligationAccess().getExpirationAssignment_3_1_3_1(), "rule__Obligation__ExpirationAssignment_3_1_3_1");
					put(grammarAccess.getRequestAccess().getStubAssignment_1_1(), "rule__Request__StubAssignment_1_1");
					put(grammarAccess.getRequestAccess().getNameAssignment_3(), "rule__Request__NameAssignment_3");
					put(grammarAccess.getRequestAccess().getAttributesAssignment_4(), "rule__Request__AttributesAssignment_4");
					put(grammarAccess.getAttributeReqAccess().getNameAssignment_1(), "rule__AttributeReq__NameAssignment_1");
					put(grammarAccess.getAttributeReqAccess().getValueAssignment_3(), "rule__AttributeReq__ValueAssignment_3");
					put(grammarAccess.getAttributeReqAccess().getValueAssignment_4_1(), "rule__AttributeReq__ValueAssignment_4_1");
					put(grammarAccess.getAttributeNameAccess().getCategoryAssignment_0(), "rule__AttributeName__CategoryAssignment_0");
					put(grammarAccess.getAttributeNameAccess().getIdAssignment_2(), "rule__AttributeName__IdAssignment_2");
					put(grammarAccess.getPDPAccess().getPdpAlgAssignment_0(), "rule__PDP__PdpAlgAssignment_0");
					put(grammarAccess.getPDPAccess().getPolSetAssignment_1(), "rule__PDP__PolSetAssignment_1");
					put(grammarAccess.getAbstractPolicyInclAccess().getNewPolicyAssignment_0(), "rule__AbstractPolicyIncl__NewPolicyAssignment_0");
					put(grammarAccess.getAbstractPolicyInclAccess().getRefPolAssignment_1_1(), "rule__AbstractPolicyIncl__RefPolAssignment_1_1");
					put(grammarAccess.getPolicySetAccess().getNameAssignment_1(), "rule__PolicySet__NameAssignment_1");
					put(grammarAccess.getPolicySetAccess().getPolSetAlgAssignment_3(), "rule__PolicySet__PolSetAlgAssignment_3");
					put(grammarAccess.getPolicySetAccess().getTargetAssignment_4_1(), "rule__PolicySet__TargetAssignment_4_1");
					put(grammarAccess.getPolicySetAccess().getPoliciesAssignment_6(), "rule__PolicySet__PoliciesAssignment_6");
					put(grammarAccess.getPolicySetAccess().getOblAssignment_7_1(), "rule__PolicySet__OblAssignment_7_1");
					put(grammarAccess.getAlgAccess().getIdAlgAssignment_0(), "rule__Alg__IdAlgAssignment_0");
					put(grammarAccess.getAlgAccess().getFStrategyAssignment_1_1(), "rule__Alg__FStrategyAssignment_1_1");
					put(grammarAccess.getRuleAccess().getNameAssignment_1(), "rule__Rule__NameAssignment_1");
					put(grammarAccess.getRuleAccess().getEffectAssignment_3(), "rule__Rule__EffectAssignment_3");
					put(grammarAccess.getRuleAccess().getTargetAssignment_4_1(), "rule__Rule__TargetAssignment_4_1");
					put(grammarAccess.getRuleAccess().getOblAssignment_5_1(), "rule__Rule__OblAssignment_5_1");
					put(grammarAccess.getAndExpressionAccess().getRightAssignment_1_2(), "rule__AndExpression__RightAssignment_1_2");
					put(grammarAccess.getOrExpressionAccess().getRightAssignment_1_2(), "rule__OrExpression__RightAssignment_1_2");
					put(grammarAccess.getNotExpressionAccess().getArgAssignment_1(), "rule__NotExpression__ArgAssignment_1");
					put(grammarAccess.getFunctionAccess().getFunctionIdAssignment_0(), "rule__Function__FunctionIdAssignment_0");
					put(grammarAccess.getFunctionAccess().getArg1Assignment_2_0(), "rule__Function__Arg1Assignment_2_0");
					put(grammarAccess.getFunctionAccess().getAtt1Assignment_2_1_2(), "rule__Function__Att1Assignment_2_1_2");
					put(grammarAccess.getFunctionAccess().getArg2Assignment_4_0(), "rule__Function__Arg2Assignment_4_0");
					put(grammarAccess.getFunctionAccess().getAtt2Assignment_4_1_2(), "rule__Function__Att2Assignment_4_1_2");
					put(grammarAccess.getDeclaredFunctionAccess().getFunctionIdAssignment_0(), "rule__DeclaredFunction__FunctionIdAssignment_0");
					put(grammarAccess.getDeclaredFunctionAccess().getArgsAssignment_2(), "rule__DeclaredFunction__ArgsAssignment_2");
					put(grammarAccess.getDeclaredFunctionAccess().getArgsAssignment_3_1(), "rule__DeclaredFunction__ArgsAssignment_3_1");
					put(grammarAccess.getSetAccess().getArgsAssignment_1_0(), "rule__Set__ArgsAssignment_1_0");
					put(grammarAccess.getSetAccess().getArgsAssignment_1_1_1(), "rule__Set__ArgsAssignment_1_1_1");
					put(grammarAccess.getStringLiteralAccess().getValueAssignment(), "rule__StringLiteral__ValueAssignment");
					put(grammarAccess.getBooleanLiteralAccess().getValueAssignment(), "rule__BooleanLiteral__ValueAssignment");
					put(grammarAccess.getIntLiteralAccess().getValueAssignment(), "rule__IntLiteral__ValueAssignment");
					put(grammarAccess.getDoubleLiteralAccess().getValueAssignment(), "rule__DoubleLiteral__ValueAssignment");
					put(grammarAccess.getDateLiteralAccess().getValueAssignment(), "rule__DateLiteral__ValueAssignment");
					put(grammarAccess.getTimeLiteralAccess().getValueAssignment(), "rule__TimeLiteral__ValueAssignment");
					put(grammarAccess.getFacplAccess().getUnorderedGroup(), "rule__Facpl__UnorderedGroup");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			it.unifi.xtext.facpl.ui.contentassist.antlr.internal.InternalFacpl2Parser typedParser = (it.unifi.xtext.facpl.ui.contentassist.antlr.internal.InternalFacpl2Parser) parser;
			typedParser.entryRuleFacpl();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public Facpl2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Facpl2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
