/*
 * generated by Xtext
 */
package it.unifi.xtext.facpl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import it.unifi.xtext.facpl.ui.internal.Facpl2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Facpl2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Facpl2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Facpl2Activator.getInstance().getInjector(Facpl2Activator.IT_UNIFI_XTEXT_FACPL_FACPL2);
	}
	
}
