/*
 * generated by Xtext
 */
package it.unifi.xtext.facpl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import it.unifi.xtext.facpl2.ui.syntaxcoloring.SyntaxHighlighting;
import it.unifi.xtext.facpl2.ui.syntaxcoloring.TokenHighlight;


/**
 * Use this class to register components to be used within the IDE.
 */
public class Facpl2UiModule extends it.unifi.xtext.facpl.ui.AbstractFacpl2UiModule {
	public Facpl2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration>bindIHighlightingConfiguration() {
		return SyntaxHighlighting.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingConfiguration() {
		return TokenHighlight.class;
	}

	public Class<? extends org.eclipse.xtext.ui.wizard.IProjectCreator> bindIProjectCreator() {
		return it.unifi.xtext.facpl.ui.wizard.Facpl2ProjectCreatorCustom.class;
	}
	
		
}
